# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            CodeLib
tagline:          'A Curated Code Collection'
description:      'Quality code, Something to stop you working the weekend Sir?'
url:              http://lanyon.getpoole.com

author:
  name:           'David Hewitt'
  url:            http://codelib.alteredlife.co.uk/

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/blindjustis/codeLib
